finish mempool add apis
logos-co/nomos-node pull request #489
Opened 2023-10-30 02:35 UTC by al8n

2023-10-30 09:13 UTC, danielSanchezQ commented on nodes/nomos-node-api/src/http/backend/axum.rs
> +        (status = 200, description = "add transaction to the mempool"),
We need to be consistent in descriptions. I have seen usually we capitalize them. Tiny details.

2023-10-30 11:21 UTC, zeegomo requested changes

2023-10-30 11:21 UTC, zeegomo commented on nodes/nomos-node-api/src/http/mempool.rs
> +    }
We don't need two different functions for this, they're the same service with different generics

2023-10-30 11:21 UTC, zeegomo commented on nodes/nomos-node-api/src/http/backend/axum.rs
> +            .route("/mempool/add/cert", routing::post(add_cert))
The concept of a mempool is the same for both, I don't have strong opinions on this but there might be suggestions on the OpenAPI standard on how to handle it

2023-10-30 11:21 UTC, zeegomo commented on nodes/nomos-node-api/src/http/backend/axum.rs
> +    pub cert_mempool: OverwatchHandle,
why do we need to keep adding handles?

2023-10-31 08:57 UTC, danielSanchezQ approved these changes

2023-11-01 07:28 UTC, merged